version: '3.3'
services:
  web:
    image: yanivomc/spring-music:latest
    ports:
      - 8080:8080
  redisdb:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:latest
    ports:
      - 80:80
